import type { ExtensionStateContextType } from "../../../../webview-ui/src/context/ExtensionStateContext"
import { ORGANIZATION_ALLOW_ALL, DEFAULT_CHECKPOINT_TIMEOUT_SECONDS, openRouterDefaultModelId } from "@roo-code/types"
import { defaultModeSlug, defaultPrompts } from "@roo/modes"
import { experimentDefault } from "@roo/experiments"

/**
 * Comprehensive default values for ExtensionStateContextType
 * Mirrors the defaults from ExtensionStateContextProvider to ensure Storybook
 * matches production behavior.
 *
 * When defaults change in ExtensionStateContextProvider, update this file accordingly.
 */
export const createDefaultExtensionState = (): ExtensionStateContextType => {
	// No-op function for all setters
	const noop = () => {}

	return {
		// ExtensionState defaults (from useState<ExtensionState>)
		apiConfiguration: {},
		version: "",
		clineMessages: [],
		taskHistoryFullLength: 0,
		taskHistoryVersion: 0,
		shouldShowAnnouncement: false,
		allowedCommands: [],
		deniedCommands: [],
		soundEnabled: false,
		soundVolume: 0.5,
		ttsEnabled: false,
		ttsSpeed: 1.0,
		diffEnabled: false,
		enableCheckpoints: true,
		checkpointTimeout: DEFAULT_CHECKPOINT_TIMEOUT_SECONDS,
		fuzzyMatchThreshold: 1.0,
		language: "en",
		writeDelayMs: 1000,
		browserViewportSize: "900x600",
		screenshotQuality: 75,
		terminalOutputLineLimit: 500,
		terminalOutputCharacterLimit: 50000,
		terminalShellIntegrationTimeout: 4000,
		mcpEnabled: true,
		enableMcpServerCreation: false,
		remoteControlEnabled: false,
		taskSyncEnabled: false,
		featureRoomoteControlEnabled: false,
		alwaysApproveResubmit: false,
		alwaysAllowWrite: true,
		alwaysAllowReadOnly: true,
		requestDelaySeconds: 5,
		currentApiConfigName: "default",
		listApiConfigMeta: [],
		mode: defaultModeSlug,
		customModePrompts: defaultPrompts,
		customSupportPrompts: {},
		experiments: experimentDefault,
		enhancementApiConfigId: "",
		dismissedNotificationIds: [],
		commitMessageApiConfigId: "",
		ghostServiceSettings: {},
		condensingApiConfigId: "",
		customCondensingPrompt: "",
		yoloGatekeeperApiConfigId: "",
		hasOpenedModeSelector: false,
		autoApprovalEnabled: true,
		customModes: [],
		maxOpenTabsContext: 20,
		maxWorkspaceFiles: 200,
		cwd: "",
		browserToolEnabled: true,
		telemetrySetting: "unset",
		showRooIgnoredFiles: true,
		showAutoApproveMenu: false,
		renderContext: "sidebar",
		maxReadFileLine: -1,
		maxImageFileSize: 5,
		maxTotalImageSize: 20,
		pinnedApiConfigs: {},
		terminalZshOhMy: false,
		maxConcurrentFileReads: 5,
		allowVeryLargeReads: false,
		terminalZshP10k: false,
		terminalZdotdir: false,
		terminalCompressProgressBar: true,
		historyPreviewCollapsed: false,
		showTaskTimeline: true,
		sendMessageOnEnter: true,
		showTimestamps: true,
		kilocodeDefaultModel: openRouterDefaultModelId,
		reasoningBlockCollapsed: true,
		cloudUserInfo: null,
		cloudIsAuthenticated: false,
		cloudOrganizations: [],
		sharingEnabled: false,
		organizationAllowList: ORGANIZATION_ALLOW_ALL,
		organizationSettingsVersion: -1,
		autoCondenseContext: true,
		autoCondenseContextPercent: 100,
		profileThresholds: {},
		codebaseIndexConfig: {
			codebaseIndexEnabled: true,
			codebaseIndexQdrantUrl: "http://localhost:6333",
			codebaseIndexEmbedderProvider: "openai",
			codebaseIndexEmbedderBaseUrl: "",
			codebaseIndexEmbedderModelId: "",
			codebaseIndexSearchMaxResults: undefined,
			codebaseIndexSearchMinScore: undefined,
		},
		codebaseIndexModels: { ollama: {}, openai: {} },
		alwaysAllowUpdateTodoList: true,
		includeDiagnosticMessages: true,
		maxDiagnosticMessages: 50,
		openRouterImageApiKey: "",
		kiloCodeImageApiKey: "",
		autoPurgeEnabled: false,
		autoPurgeDefaultRetentionDays: 30,
		autoPurgeFavoritedTaskRetentionDays: null,
		autoPurgeCompletedTaskRetentionDays: 30,
		autoPurgeIncompleteTaskRetentionDays: 7,
		autoPurgeLastRunTimestamp: undefined,
		openRouterImageGenerationSelectedModel: "",
		includeCurrentTime: true,
		includeCurrentCost: true,

		// Additional context defaults (from separate useState calls)
		didHydrateState: false,
		showWelcome: false,
		theme: undefined,
		filePaths: [],
		openedTabs: [],
		commands: [],
		mcpServers: [],
		mcpMarketplaceCatalog: { items: [] },
		currentCheckpoint: undefined,
		routerModels: undefined,
		globalRules: {},
		localRules: {},
		globalWorkflows: {},
		localWorkflows: {},
		marketplaceItems: [],
		alwaysAllowFollowupQuestions: false,
		followupAutoApproveTimeoutMs: undefined,
		marketplaceInstalledMetadata: {
			project: {},
			global: {},
		},
		includeTaskHistoryInEnhance: true,
		currentTaskItem: undefined,
		currentTaskTodos: undefined,
		taskHistory: [],
		taskHistoryVersion: 0,
		hasSystemPromptOverride: undefined,
		hideCostBelowThreshold: undefined,
		hoveringTaskTimeline: undefined,
		systemNotificationsEnabled: undefined,
		yoloMode: undefined,
		machineId: undefined,

		// All setter functions as no-ops
		setShowTaskTimeline: noop,
		setSendMessageOnEnter: noop,
		setShowTimestamps: noop,
		setHideCostBelowThreshold: noop,
		setHoveringTaskTimeline: noop,
		setSystemNotificationsEnabled: noop,
		setYoloMode: noop,
		setAutoPurgeEnabled: noop,
		setAutoPurgeDefaultRetentionDays: noop,
		setAutoPurgeFavoritedTaskRetentionDays: noop,
		setAutoPurgeCompletedTaskRetentionDays: noop,
		setAutoPurgeIncompleteTaskRetentionDays: noop,
		setAutoPurgeLastRunTimestamp: noop,
		setExperimentEnabled: noop,
		setApiConfiguration: noop,
		setCustomInstructions: noop,
		setAlwaysAllowReadOnly: noop,
		setAlwaysAllowReadOnlyOutsideWorkspace: noop,
		setAlwaysAllowWrite: noop,
		setAlwaysAllowWriteOutsideWorkspace: noop,
		setAlwaysAllowExecute: noop,
		setAlwaysAllowBrowser: noop,
		setAlwaysAllowMcp: noop,
		setAlwaysAllowModeSwitch: noop,
		setAlwaysAllowSubtasks: noop,
		setAlwaysAllowFollowupQuestions: noop,
		setFollowupAutoApproveTimeoutMs: noop,
		setShowAnnouncement: noop,
		setAllowedCommands: noop,
		setDeniedCommands: noop,
		setAllowedMaxRequests: noop,
		setAllowedMaxCost: noop,
		setSoundEnabled: noop,
		setSoundVolume: noop,
		setTtsEnabled: noop,
		setTtsSpeed: noop,
		setDiffEnabled: noop,
		setEnableCheckpoints: noop,
		setCheckpointTimeout: noop,
		setBrowserViewportSize: noop,
		setFuzzyMatchThreshold: noop,
		setWriteDelayMs: noop,
		setScreenshotQuality: noop,
		setTerminalOutputLineLimit: noop,
		setTerminalOutputCharacterLimit: noop,
		setTerminalShellIntegrationTimeout: noop,
		setTerminalShellIntegrationDisabled: noop,
		setTerminalZdotdir: noop,
		setMcpEnabled: noop,
		setEnableMcpServerCreation: noop,
		setRemoteControlEnabled: noop,
		setTaskSyncEnabled: noop,
		setFeatureRoomoteControlEnabled: noop,
		setAlwaysApproveResubmit: noop,
		setRequestDelaySeconds: noop,
		setCurrentApiConfigName: noop,
		setListApiConfigMeta: noop,
		setMode: noop,
		setCustomModePrompts: noop,
		setCustomSupportPrompts: noop,
		setEnhancementApiConfigId: noop,
		markNotificationAsDismissed: noop,
		setGhostServiceSettings: noop,
		setCommitMessageApiConfigId: noop,
		setShowAutoApproveMenu: noop,
		setAutoApprovalEnabled: noop,
		setCustomModes: noop,
		setMaxOpenTabsContext: noop,
		setMaxWorkspaceFiles: noop,
		setBrowserToolEnabled: noop,
		setTelemetrySetting: noop,
		setShowRooIgnoredFiles: noop,
		setRemoteBrowserEnabled: noop,
		setAwsUsePromptCache: noop,
		setMaxReadFileLine: noop,
		setMaxImageFileSize: noop,
		setMaxTotalImageSize: noop,
		setPinnedApiConfigs: noop,
		setTerminalCompressProgressBar: noop,
		togglePinnedApiConfig: noop,
		setHistoryPreviewCollapsed: noop,
		setReasoningBlockCollapsed: noop,
		setHasOpenedModeSelector: noop,
		setAutoCondenseContext: noop,
		setAutoCondenseContextPercent: noop,
		setCondensingApiConfigId: noop,
		setCustomCondensingPrompt: noop,
		setYoloGatekeeperApiConfigId: noop,
		setProfileThresholds: noop,
		setAlwaysAllowUpdateTodoList: noop,
		setIncludeDiagnosticMessages: noop,
		setMaxDiagnosticMessages: noop,
		setIncludeTaskHistoryInEnhance: noop,
		setIncludeCurrentTime: noop,
		setIncludeCurrentCost: noop,
	} as ExtensionStateContextType
}
